### ISSUE TITLE
搜索失败

### ISSUE THREAD

**Issue by panwanke** [JoysKang/notion-search#1]
折腾了很久，最后都搜索失败。
尝试方法：用网页打开notion，在页面中开启搜索功能。资源检测到search请求，复制里面的cookie和space_id。
尝试了只复制cookie里的token_v2，或者space_id不加双引号。也尝试切换刷新页面等重新获取cookie和space_id，均以失败告终。
第二天尝试申请notion官网api，通过api申请，依然失败。

**Comment by panwanke** [comment]
看了下源码，可能与header，body信息有关。1. notion版本一直没更新  2. 新版代码逻辑可能有变动？

**Comment by JoysKang** [comment]
cookie 复制 cookie: 后的全部内容， space_id 只复制引号里边的
已复测  能够正常搜索

**Comment by zhponng** [comment]
同样的问题，cookie和spaceid均已设置，搜索一直失败。我用的mac，看大神截图用的windows，不知是否跟系统有关系。
![image](https://user-images.githubusercontent.com/88756812/136650124-fa25b43e-982f-45a0-849f-73d7cbdbb2fc.png)

**Comment by JoysKang** [comment]
有什么提示或者表现吗   我是mac  开个虚拟机win 下也正常   百思不得姐 @zhponng

**Comment by zhponng** [comment]
没什么表现，设置好参数后，输入关键字进行搜索，几秒或者几十秒后提示未查找到匹配项，而网页端可以正常搜到。v2ex上大神的帖子下也反馈过这个问题了

**Comment by panwanke** [comment]
> 没什么表现，设置好参数后，输入关键字进行搜索，几秒或者几十秒后提示未查找到匹配项，而网页端可以正常搜到。v2ex上大神的帖子下也反馈过这个问题了

我同样是没有反应。尝试了很多方式也没有成功...
不知道作者用的什么方式获得的cookie？
我是chrome游览器 > notion主界面 > 搜索 > 捕获search post请求 > 复制cookies

**Comment by JoysKang** [comment]
是否设置了代理？  取消代理 & 设置全局代理试下

**Comment by JoysKang** [comment]
@Asynchro-Epool 一样的操作  也可以 鼠标单击cookies->右键copy value

**Comment by Neo-peng** [comment]
同样macos搜索无结果。
我开了surge的代理，抓包后发现好像没有向notion.so的search api发起请求，猜测应该是调用api方面问题

**Comment by JoysKang** [comment]
可以获取下最新的 token 试下    utools 暂时还没有找到合适的错误日志收集  没法分析   我使用一切正常...

**Comment by Neo-peng** [comment]
> 可以获取下最新的 token 试下 utools 暂时还没有找到合适的错误日志收集 没法分析 我使用一切正常...

好像是utools的锅。我这样测试了一波
1. 用postman取到了正确的搜索结果
2. 然后用postman的生成的代码去utools测试
3. 然后抓包，发现utools没有向notion的api发起过请求
utools有没有console，没有console调试起来好麻烦

**Comment by JoysKang** [comment]
> 好像是utools的锅。我这样测试了一波
> 
> 1. 用postman取到了正确的搜索结果
> 2. 然后用postman的生成的代码去utools测试
> 3. 然后抓包，发现utools没有向notion的api发起过请求
>    utools有没有console，没有console调试起来好麻烦

可以本地加载该项目  然后去插件市场安装开发者工具  本地调试下
![image](https://user-images.githubusercontent.com/11786681/143325940-42381826-4ccd-4c1c-ac61-fbf4f660f14e.png)

![image](https://user-images.githubusercontent.com/11786681/143325980-6d6c3969-d3f3-41fe-91b3-f1e124c6b7a4.png)

**Comment by Neo-peng** [comment]
> > 好像是utools的锅。我这样测试了一波
> > 
> > 1. 用postman取到了正确的搜索结果
> > 2. 然后用postman的生成的代码去utools测试
> > 3. 然后抓包，发现utools没有向notion的api发起过请求
> >    utools有没有console，没有console调试起来好麻烦
> 
> 可以本地加载该项目 然后去插件市场安装开发者工具 本地调试下 ![image](https://user-images.githubusercontent.com/11786681/143325940-42381826-4ccd-4c1c-ac61-fbf4f660f14e.png)
> 
> ![image](https://user-images.githubusercontent.com/11786681/143325980-6d6c3969-d3f3-41fe-91b3-f1e124c6b7a4.png)

感谢帮忙。今天调试了一下，本地测试通过了，问题好像是处在fetch的过程，但是具体问题出在哪里搞不清楚。这是我调整过的那部分代码，其余部分都没有变。
`const searchResult = [];
  const cookie = utools.dbStorage.getItem('cookie');
  const spaceId = utools.dbStorage.getItem('spaceId');

  if (!cookie || !spaceId) {
    utools.showNotification('cookie 或 spaceId 未配置');
    return [];
  }

  var myHeaders = new Headers();

  myHeaders.append('Cookie', cookie);
  myHeaders.append('Content-Type', 'application/json');

  var raw = {
    type: 'BlocksInSpace',
    query: searchWord,
    spaceId: spaceId,
    limit: 9,
    filters: {
      isDeletedOnly: false,
      excludeTemplates: false,
      isNavigableOnly: false,
      requireEditPermissions: false,
      ancestors: [],
      createdBy: [],
      editedBy: [],
      lastEditedTime: {},
      createdTime: {},
    },
    sort: 'Relevance',
    source: 'quick_find',
  };

  raw = JSON.stringify(raw);
  var requestOptions = {
    method: 'POST',
    headers: myHeaders,
    body: raw,
    redirect: 'follow',
  };
  let jsonData = '';
  await fetch('https://www.notion.so/api/v3/search', requestOptions)
    .then((response) => response.json())
    .then((data) => {
      jsonData = data;
      // console.log(jsonData);
    })
    .catch((error) => console.log('error', error));

  // console.log(jsonData);
  // console.timeEnd('test2')
  const results = jsonData.results;
  const recordMap = jsonData.recordMap;
`
虽然这样解决了我的问题，但是我还是不知道问题出在哪里。而且我在console里查network，发现即使搜索成功network也没有向notion.so的网络记录，另外我还专门用外部的抓包工具看了utools发起的网络请求，也没有发现utools向notion.so发起的请求。但结果确实搜索出来了，真的是很诡异。。。

**Comment by JoysKang** [comment]
辛苦，根据你的代码发了一版。丢失的 notion-client-version 也已补上。

**Comment by JoysKang** [comment]
插件审核通过  可以再试下  反馈下

**Comment by zhponng** [comment]
> 插件审核通过 可以再试下 反馈下

我这更新后可以了，感谢 @JoysKang ， 感谢 @Neo-peng

**Comment by JoysKang** [comment]
@zhponng 感谢反馈 祝使用愉快
